name: Latest Changes

on:
  pull_request_target:
    branches:
      - develop
    types:
      - closed
  # For manually triggering it
  workflow_dispatch:
    inputs:
      number:
        description: PR number
        required: true

jobs:
  latest-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: tiangolo/latest-changes@0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          latest_changes_file: release-notes.md
          latest_changes_header: "## Latest Changes"
          end_regex: "^## "
          label_header_prefix: "### "