name: Latest Changes

on:
  pull_request_target:
    branches:
      - develop
    types:
      - closed
  # For manually triggering it
  workflow_dispatch:
    inputs:
      number:
        description: PR number
        required: true

jobs:
  latest-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: tiangolo/latest-changes@0.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          latest_changes_file: release-notes.md
          latest_changes_header: "## Latest Changes"
          end_regex: "^## "
          label_header_prefix: "### "
          labels: >
            [
              {"label": "breaking", "header": "Breaking Changes"},
              {"label": "feature", "header": "Features"},
              {"label": "bug", "header": "Fixes"},
              {"label": "refactor", "header": "Refactors"},
              {"label": "upgrade", "header": "Upgrades"},
              {"label": "docs", "header": "Docs"},
              {"label": "infra", "header": "Infrastructure"},
              {"label": "internal", "header": "Internal"},
              {"label": "chore", "header": "Chore"}
            ]